Don't render the video unless there is one (#509)
Rollbar error:

NoMethodError: undefined method `html_safe' for nil:NilClass
Did you mean? html_safe?
File "/var/app/current/app/views/homeowners/about_videos/_video.html.erb", line 2, in _app_views_homeowners_about_videos__video_html_erb__4562326968325666729_70254300759960

This error is seen if there is no video configured for the hoozzi site.

Since it's site-wide, and a video has now been configured, it's unlikely to appear again, fixing this for good practice.